Repository YadavGulshan/MedAlthea, pull requests merged in 2022-01, with the labels that each got.

#2 Json web tokenization is done!
  backend/api/urls.py
  backend/api/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/db.sqlite3
  backend/pharmacy/admin.py
  backend/pharmacy/api/__init__.py
  backend/pharmacy/api/serializers.py
  backend/pharmacy/api/urls.py
  backend/pharmacy/api/views.py
  backend/pharmacy/migrations/0001_initial.py
  backend/pharmacy/migrations/0002_remove_medical_id_medical_medicalid_and_more.py
  backend/pharmacy/migrations/0002_remove_medical_image.py
  backend/pharmacy/migrations/0003_alter_medical_phone.py
  backend/pharmacy/migrations/0003_medical_image.py
  backend/pharmacy/models.py
  setup.sh
Labels: enhancement, help wanted

#5 review and merge
  README.md
  apps/Frames/Nearby_shops.py
  apps/Frames/search_results.py
  apps/Frames/welcome_frame.py
  apps/app.py
  apps/requirements.txt
  apps/root.py
Labels: documentation, enhancement

#6 Cleaned the previous code and also fixed the image issue with api.
  backend/backend/settings.py
  backend/db.sqlite3
  backend/pharmacy/api/serializers.py
  backend/pharmacy/api/urls.py
  backend/pharmacy/api/views.py
  backend/pharmacy/migrations/0004_alter_medical_image_alter_medical_website.py
  backend/pharmacy/models.py
  requirements.txt
Labels: enhancement

#8 Sign Up completed
  backend/db.sqlite3
  backend/pharmacy/api/serializers.py
Labels: documentation, enhancement

#10 Alpha
  .gitignore
  .nvimlog
  apps/Frames/search_results.py
  apps/Frames/welcome_frame.py
  apps/app.py
  apps/images/capsule.png
  backend/pharmacy/admin.py
  backend/pharmacy/models.py
Labels: bug, wontfix
