Repository YadavGulshan/MedAlthea, pull requests merged in 2022-02, with the labels that each got.

#14 There no big change or modification
  .gitignore
  apps/Fonts/OFL.txt
  apps/Fonts/SourceSerifPro-Black.ttf
  apps/Fonts/SourceSerifPro-BlackItalic.ttf
  apps/Fonts/SourceSerifPro-Bold.ttf
  apps/Fonts/SourceSerifPro-BoldItalic.ttf
  apps/Fonts/SourceSerifPro-ExtraLight.ttf
  apps/Fonts/SourceSerifPro-ExtraLightItalic.ttf
  apps/Fonts/SourceSerifPro-Italic.ttf
  apps/Fonts/SourceSerifPro-Light.ttf
  apps/Fonts/SourceSerifPro-LightItalic.ttf
  apps/Fonts/SourceSerifPro-Regular.ttf
  apps/Fonts/SourceSerifPro-SemiBold.ttf
  apps/Fonts/SourceSerifPro-SemiBoldItalic.ttf
  apps/Frames/welcome_frame.py
  apps/resourses.txt
  backend/pharmacy/migrations/0005_medicineclass.py
  backend/pharmacy/models.py
Labels: enhancement

#15 Added distance calculating api
  .gitignore
  README.md
  assets/logo.jpg
  assets/logo.svg
  backend/ShowNearbyMedicalShops.drawio
  backend/pharmacy/api/urls.py
  backend/pharmacy/api/views/mapper/__init__.py
  backend/pharmacy/api/views/mapper/display_nearby_medical.py
  backend/pharmacy/api/views/mapper/distance.py
  backend/pharmacy/api/views/medical/list.py
  backend/pharmacy/api/views/medicine/list.py
  backend/pharmacy/api/views/userActions/register.py
  backend/pharmacy/migrations/0001_initial.py
  backend/pharmacy/migrations/0002_remove_medical_id_medical_medicalid_and_more.py
  backend/pharmacy/migrations/0003_alter_medical_phone.py
  backend/pharmacy/migrations/0004_alter_medical_image_alter_medical_website.py
  backend/pharmacy/migrations/0005_medicineclass.py
  backend/pharmacy/models.py
Labels: documentation, enhancement

#16 Search by pincode
  backend/pharmacy/api/urls.py
  backend/pharmacy/api/views/mapper/display_nearby_medical.py
  backend/pharmacy/api/views/mapper/distance.py
Labels: enhancement

#17 Added docker file for backend
  backend/Dockerfile
  backend/pharmacy/api/urls.py
Labels: enhancement

#18 Created a Login Frame
  apps/Frames/loginform.ui
Labels: enhancement

#19 Created SignUp frame_01
  apps/Frames/signup(frame_1).ui
Labels: enhancement

#20 Wrote some tests!!!
  .github/workflows/django.yml
  backend/pharmacy/api/tests.py
  backend/pharmacy/api/tests/__init__.py
  backend/pharmacy/api/tests/test_user.py
  backend/pharmacy/api/urls.py
  backend/pharmacy/api/views/mapper/__init__.py
  backend/pharmacy/api/views/medical/list.py
  backend/pharmacy/api/views/medicine/list.py
  backend/pharmacy/api/views/userActions/register.py
  backend/pharmacy/migrations/0002_alter_medical_image.py
  backend/pharmacy/models.py
Labels: enhancement

#21 tried creating function to signin frame
  apps/Frames/loginform.ui
  apps/app.py
Labels: enhancement

#33 Login Frame done
  apps/Frames/functions/getLogin.py
  apps/Frames/loginform.ui
  apps/Frames/loginform.ui.autosave
  apps/Frames/searchFrame.ui
  apps/Frames/signUp.py
  apps/Frames/signUp.ui
  apps/token.sqlite3
Labels: enhancement

#35 fix for signup buttons
  .gitignore
  apps/Frames/functions/localdb.py
  apps/Frames/login.py
  apps/Frames/searchFrame.py
  apps/Frames/searchFrame.ui
  apps/Frames/signUp.py
  apps/app.py
  apps/token.sqlite3
Labels: enhancement

#37 working on search frame and fix on signup page
  apps/Frames/searchFrame.ui
  apps/Frames/signUp.py
  apps/Frames/signUp.ui
  apps/app.py
  apps/images/search.png
Labels: enhancement

#42 Update .gitignore
  .gitignore
Labels: enhancement

#43 Added a missing feature for getting the list of medicine of current medical owner.
  APIdoc.md
  backend/pharmacy/api/tests/unit/medicial/test_medical_medicine_list.py
  backend/pharmacy/api/urls.py
  backend/pharmacy/api/views/medical/__init__.py
  backend/pharmacy/api/views/medical/medicine.py
  backend/pharmacy/migrations/0001_initial.py
  backend/pharmacy/migrations/0002_alter_medical_image.py
  backend/pharmacy/models.py
  docs/AUTH.md
  docs/medicalUserDoc.md
  docs/normalUserDOc.md
Labels: documentation

#44 fixed some serious bugs...
  backend/pharmacy/api/urls.py
  backend/pharmacy/api/views/medicine/list.py
  backend/pharmacy/api/views/userActions/register.py
Labels: bug, documentation

#48 Added hanlers and did some changes in UI
  apps/Frames/functions/getData.py
  apps/Frames/functions/getLogin.py
  apps/Frames/functions/getRegister.py
  apps/Frames/functions/localdb.py
  apps/Frames/searchFrame.py
  apps/Frames/searchFrame.ui
  apps/Frames/signUp.py
  apps/Frames/signup(frame_2).ui
  apps/app.py
  apps/images/capsule.png
Labels: enhancement

#49 modification in main application
  apps/Frames/functions/getData.py
  apps/Frames/functions/getLogin.py
  apps/Frames/functions/getRegister.py
  apps/Frames/login.py
  apps/Frames/message.py
  apps/Frames/searchFrame.py
  apps/app.py
Labels: enhancement
